language: generic
branches:
  only:
  - master
stages:
  - name: test
    if: branch = master AND \
        type = pull_request
  - name: deploy
    if: branch = master AND \
        type = push
jobs:
  include:
    - stage: test
      script: ./script/test
    - stage: deploy
      script: ./script/deploy
before_script:
- chmod +x ./script/test
- chmod +x ./script/deploy
before_install:
- mkdir credentials
- touch credentials/isomer-google-credentials.json
- openssl aes-256-cbc -K $encrypted_63f297c768a8_key -iv $encrypted_63f297c768a8_iv
  -in isomer-google-credentials.json.enc -out credentials/isomer-google-credentials.json
  -d